#ifndef COVER_HTTPCLIENT_GRAPHQL_EXPORT_H
#define COVER_HTTPCLIENT_GRAPHQL_EXPORT_H

#include <util/coExport.h>

#if defined(coGraphQL_EXPORTS)
#define GRAPHQLCLIENTEXPORT COEXPORT
#else
#define GRAPHQLCLIENTEXPORT COIMPORT
#endif

#endif // COVER_HTTPCLIENT_GRAPQHL_EXPORT_H