name: Make Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # workflow_dispatch:
  # release:
  #   types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: Install build environment
        run: >
          pacman -Sy --noconfirm && pacman -S --noconfirm base-devel git cmake ninja sudo

      - name: Init environment
        run: >
          useradd --create-home builder && usermod -aG wheel builder && echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "CI/CD"

      - name: Change permission for covise
        run: |
          chmod -R 777 $GITHUB_WORKSPACE

      - name: Build Package
        run: |
          sudo -u builder bash -c "cd '$GITHUB_WORKSPACE' && makepkg -s"

      - name: Upload package as artifact
        uses: actions/upload-artifact@v4
        with: 
          name: covise-arch-package
          path: "*.pkg.tar.zst"

  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Package source code including submodules
        uses: qmonnet/git-archive-all-action@v1
        with:
          output-files: covise-${{ github.ref_name }}.tar.gz covise-${{ github.ref_name }}.zip
          force-submodules: true

      - name: Create draft release and add artifacts
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: covise-*
